emotion_to_mood = {
    "admiration": "uplifting",
    "amusement": "upbeat",
    "anger": "intense",
    "annoyance": "chill",
    "approval": "happy",
    "caring": "soothing",
    "confusion": "suspense",
    "curiosity": "thrill",
    "desire": "upbeat",
    "disappointment": "melancholy",
    "disapproval": "dark",
    "disgust": "grunge",
    "embarrassment": "lofi",
    "excitement": "energetic",
    "fear": "ambient",
    "gratitude": "uplifting",
    "grief": "soft rock",
    "joy": "happy",
    "love": "romantic",
    "nervousness": "calm",
    "optimism": "upbeat",
    "pride": "confident",
    "realization": "thoughtful",
    "relief": "peaceful",
    "remorse": "reflective",
    "sadness": "melancholy",
    "surprise": "eclectic",
    "neutral": "ambient"
}